var num1 =  (10 + "20");
console.log(num1);
var num2 = (9 - "5");
console.log(num2);
var num3 = (5 + 5);
console.log(num3);
var num4 = ("10 " + "10");
console.log(num4);
var bugOnJs = 9 - "5";
console.log(bugOnJs);
var n = false - true;
console.log(n);
console.log("Another Items");
console.log(" " + " ");
console.log(" " + 0);
